[build]
  # 建置命令 - 在 src/Projects/TailorMed/track 目錄中執行
  command = "npm install && npm run build"
  
  # 發布目錄 - 相對於建置目錄的路徑
  publish = "dist/Projects/TailorMed/track"

[[redirects]]
  # 處理 SPA 路由（如果需要）
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
[[headers]]
  # 為所有頁面添加安全標頭
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

